name: spaco
description: cowork mate

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  flutter_feather_icons: ^2.0.0+1
  get:
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master
  introduction_screen:
  cloud_firestore:
  firebase_core:
  flutter_firebase_auth_facade:
  firebase_storage: ^10.1.0
  google_sign_in:
  firebase_auth:
  pin_code_fields: ^7.3.0
  google_nav_bar: ^5.0.5
  path_provider:
  intl:
  flutter_launcher_icons: ^0.9.3
  date_time_picker: ^2.1.0
  flutter_svg: ^1.1.1+1
  avatar_view: ^1.0.1
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  photo_view: ^0.13.0
  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.3.0
  flutter_custom_clippers: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/spaco_logo_green_512.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/svg/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
